# Disco / ruta en el HOST KVM
adi_nfs_device: "/dev/sda1"                 # Format realizado
adi_nfs_mount: "/var/lib/one/datastores"
adi_nfs_fstype: "xfs"                       # "auto"

# Export NFS (KVM -> frontend)
adi_nfs_frontend_host: "10.101.102.11"  # IP: "10.101.102.11"
adi_nfs_export_opts: "rw,sync,no_root_squash,no_subtree_check,nohide"

# Cliente NFS FRONTEND 
adi_nfs_server: "10.101.102.12"            # IP del KVM: "10.101.102.12"

