# Disco / ruta en el HOST KVM
adi_nfs_device: "/dev/sda1"                 # Format realizado
adi_nfs_mount: "/var/lib/one/datastores"
adi_nfs_fstype: "xfs"                       # "auto"

# Export NFS (KVM -> frontend)
adi_nfs_frontend_host: "192.168.3.51"  # IP: "192.168.3.51"
adi_nfs_export_opts: "rw,sync,no_root_squash,no_subtree_check,nohide"

# Cliente NFS FRONTEND 
adi_nfs_server: "192.168.3.50"            # IP del KVM: "192.168.3.50"

